Feat/add snowflake plots package
anyonlabs/Snowflake.jl pull request #113
Opened 2023-03-30 20:50 UTC by npoirie1

Moves the visualization tools to a new package called SnowflakePlots.jl.

Fixes #81

2023-04-05 10:50 UTC, plerouxanyon reviewed
Thanks!

I think we should remove test files since they don't test anything. We can come back later and refactor for testability.

It also needs to be updated with the latest changes in `main`.

Other than that, it looks good!

2023-04-05 21:22 UTC, npoirie1 commented
@plerouxanyon, SnowflakePlots has been updated based on the latest changes in `main`. I have also removed the tests that were in the SnowflakePlots package. Do you think that it's a good idea to have separate code coverage reports for Snowflake and SnowflakePlots?

2023-04-06 03:51 UTC, plerouxanyon commented
> @plerouxanyon, SnowflakePlots has been updated based on the latest changes in `main`. I have also removed the tests that were in the SnowflakePlots package. Do you think that it's a good idea to have separate code coverage reports for Snowflake and SnowflakePlots?

Thanks!

Regarding the coverage: If it can be easily split, then I think that would be good, but otherwise, we can keep them together for now.

2023-04-06 04:32 UTC, npoirie1 commented
> 

Splitting the coverage won't be easy. From what I can tell, it requires adding SnowflakePlots to Codecov. We should keep the coverage as is for now.

2023-04-06 11:44 UTC, plerouxanyon requested changes
Just the dependencies that need to be fixed, then we can merge.

2023-04-06 14:01 UTC, npoirie1 commented on SnowflakePlots.jl/Project.toml
> +Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
The `Test` dependency has been removed. However, the `Coverage` dependency is needed for the `coverage.jl` file. As for the `Revise` package, it is useful when developing.

2023-04-06 17:42 UTC, plerouxanyon commented on SnowflakePlots.jl/Project.toml
> +Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
The `Coverage` package is a dependency of the tests and not of `SnowflakePlots`. See https://pkgdocs.julialang.org/v1/creating-packages/#Test-specific-dependencies-in-Julia-1.2-and-above.

As for `Revise`, I still think we should remove it. We don't want to force users to use a package that they don't necessarily want. A developer could always add it to their local environment if they want to use it.

2023-04-06 17:57 UTC, npoirie1 commented on SnowflakePlots.jl/Project.toml
> +Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
`Coverage` and `Revise` are no longer dependencies.

2023-04-06 19:20 UTC, plerouxanyon approved these changes
Looks good!

2023-04-06 19:20 UTC, merged