Feat/qpu interface
anyonlabs/Snowflake.jl pull request #115
Opened 2023-04-04 14:56 UTC by fSosaRey

minimal qpu-interface

2023-04-04 18:19 UTC, plerouxanyon requested changes
Let's split this MR, one for each of the issues

* #84 
* #83 
* #85

2023-04-04 18:19 UTC, plerouxanyon commented on src/remote/run_jobs.jl
> +struct QPUService <: Service
Please rename to `AnyonQPU`

It should also only depend on client. It is going to replace the old `QPU`.

2023-04-04 18:19 UTC, plerouxanyon commented on src/remote/run_jobs.jl
> +function Base.Dict(response::HTTP.Messages.Response)
This is type piracy and could break external code if they import this package

See https://docs.julialang.org/en/v1/manual/style-guide/#Avoid-type-piracy.

2023-04-04 18:19 UTC, plerouxanyon commented on src/remote/run_jobs.jl
> +function run(qpu_service::QPUService, circuit::QuantumCircuit,num_repetitions::Integer;verbose=false)
Could you remove the verbose flag? Logging should be done using middle layers and composition, not by passing flags into functions.

2023-04-04 18:19 UTC, plerouxanyon commented on src/remote/run_jobs.jl
> +        sleep(0.2) #wait 200ms to minimize printout counts
Would you please make this a parameter of `AnyonQPU` instead?

2023-04-04 18:19 UTC, plerouxanyon commented on src/remote/run_jobs.jl
> +function submit_circuit(client::Client,circuit_json::String;verbose=false)
Submit circuit should take a circuit and number of repetitions. The fact the client serialized the circuit to JSON is an implementation detail.

2023-04-04 18:19 UTC, plerouxanyon commented on src/remote/run_jobs.jl
> +function serialize_circuit(circuit::QuantumCircuit,repetitions::Integer;indentation::Integer=4)
You should never indent JSON that is sent over the network. If you want to be able to debug this perhaps return `circuit_description` instead and call `JSON.json(...)` when making the request in `submit_circuit`.

2023-04-06 03:22 UTC, plerouxanyon commented
Please check the commits that are part of this pull request. It shows changes that have already landed in `main`.

2023-04-06 18:11 UTC, plerouxanyon requested changes

2023-04-06 18:11 UTC, plerouxanyon commented on src/anyon/run_jobs.jl
> +    )
Add the return type

2023-04-06 18:11 UTC, plerouxanyon commented on src/anyon/run_jobs.jl
> +    return body["status"]
Validate that the status is one of the expected status values.

2023-04-06 18:11 UTC, plerouxanyon commented on src/anyon/run_jobs.jl
> +        sleep(get_printout_delay(qpu)/1000)
Let's not make the wait between statuses dependent on print duration. We could want the latest status to be printed only every second but query the status every 100ms.

2023-04-06 18:11 UTC, plerouxanyon commented on src/anyon/run_jobs.jl
> +        return get_result(client,circuitID)
Don't assume that the status is now success. It might be `cancelled`.

2023-04-06 21:06 UTC, fSosaRey commented on src/anyon/run_jobs.jl
> +struct MockRequestor<:Requestor end
The doctests require the MockRequester in the library code

2023-04-07 19:16 UTC, plerouxanyon requested changes

2023-04-11 15:45 UTC, plerouxanyon requested changes

2023-04-11 16:24 UTC, fSosaRey commented on src/anyon/run_jobs.jl
> +function run_job(qpu::AnyonQPU, circuit::QuantumCircuit,num_repetitions::Integer)::Dict{String,Int}
no printout is produced in run_job()

2023-04-11 16:40 UTC, plerouxanyon commented on test/qpu_interface.jl
> +    for f in fieldnames(typeof(response))
Also, please only mark it as resolved after pushing the commit (refactoring response comparison)

2023-04-11 16:42 UTC, plerouxanyon commented on src/anyon/run_jobs.jl
> +            println(status)
Here is still a printout. Please only mark threads as resolved once a commit has been pushed.

2023-04-11 17:32 UTC, fSosaRey commented on test/qpu_interface.jl
> +    for f in fieldnames(typeof(response))
Version is the HTTP protocol version used to contruct the response

2023-04-13 19:11 UTC, plerouxanyon requested changes
![image](https://user-images.githubusercontent.com/99685336/231859533-ee81f4a5-881a-4ebc-8826-6ccf885a5ee5.png)

When I generate the documentation, the setup code appears in the docs. I expected the setup code to be hidden. Would you please check this?

Other than the setup code in the docs everything else is good to go!

2023-04-14 17:59 UTC, plerouxanyon approved these changes

2023-04-14 19:49 UTC, merged