feat: check for qubit count and presence of native gates at submission to AnyonQPU
anyonlabs/Snowflake.jl pull request #182
Opened 2023-04-26 20:11 UTC by fSosaRey

Closes #164 #166

2023-04-26 21:53 UTC, plerouxanyon requested changes

2023-04-27 16:36 UTC, fSosaRey commented on src/anyon/qpu_interface.jl
> +get_num_qubits(qpu::AbstractQPU) =
get_num_qubits(::AnyonQPU) is implemented, so either we throw a NonImplementedError for any other AbstractQPU, or the default MethodError will be thrown

2023-04-27 17:19 UTC, plerouxanyon requested changes

2023-04-27 17:19 UTC, plerouxanyon commented on src/anyon/qpu_interface.jl
> +get_num_qubits(qpu::AbstractQPU) =
I think we should remove the `get_num_qubits` from the abstract QPU interface. It means that code that depends on an AbstractQPU interface is not guaranteed to work with an AbstractQPU. It breaks the Liskov substitution principle. Allowing partial interfaces prevents us from building robust code on top of AnyonQPU.

2023-04-27 17:19 UTC, plerouxanyon commented on src/anyon/qpu_interface.jl
> +    transpiler::Transpiler=TrivialTranspiler()
Remove the transpiler argument and use `get_transpiler(qpu)`. This is meant as a user-friendly "run", but without worrying about transpilers. If the user wants to use their own transpiler then they can call transpile themselves.

2023-04-27 17:19 UTC, plerouxanyon commented on src/anyon/anyon.jl
> +get_connectivity(qpu::AnyonQPU)="1──2──3──4──5──6"
Rename to `print_connectivity(io, qpu)` and draw to `io`.

2023-04-27 17:19 UTC, plerouxanyon commented on src/anyon/anyon.jl
> +function is_native_circuit(qpu::AnyonQPU,circuit::QuantumCircuit)::Bool
It is unexpected that `is_native_circuit` throws an error if it returns a bool. I think it is better to have this return bool and throw an error in `run_job` if the circuit is not native.

2023-04-27 19:29 UTC, fSosaRey commented
Closes #167

2023-04-27 19:46 UTC, plerouxanyon requested changes

2023-04-27 19:46 UTC, plerouxanyon commented on src/anyon/qpu_interface.jl
> +print_connectivity(qpu::AbstractQPU,io::IO=stdout) =
This cannot be implemented for all QPUs. What does the connectivity of a VirtualQPU look like?

2023-04-27 20:18 UTC, plerouxanyon approved these changes

2023-04-27 20:19 UTC, merged