Docs/asynchronous jobs
anyonlabs/Snowflake.jl pull request #183
Opened 2023-04-26 22:22 UTC by plerouxanyon

Closes #163 
Closes #180

2023-04-27 21:05 UTC, fSosaRey requested changes

2023-04-27 21:05 UTC, fSosaRey commented on examples/asynchronous_jobs.jl
> +num_repititions = 200
num_repetitions

2023-04-27 21:45 UTC, plerouxanyon commented on docs/src/examples/advanced/asynchronous_jobs.md
> +# Simulate work by calculating the nth Fibonacci number slowly
Instead of memoizing the results it re-computes it everytime.

2023-04-28 09:28 UTC, plerouxanyon commented
@fSosaRey All the comments have been addressed. Would you have another look?

2023-04-28 12:34 UTC, fSosaRey approved these changes

2023-04-28 12:34 UTC, fSosaRey commented on docs/src/examples/advanced/asynchronous_jobs.md
> +If we absolutely have to have the job's result, we have no choice but to wait. Often, other work can be done while waiting for the quantum job to complete. We want to be able to suspend the `run_job`
By "suspend" I understand "pause". We want to be able to decouple the execution of `run_job` from the rest of our program?

2023-04-28 12:56 UTC, merged