Docs/pre release
anyonlabs/Snowflake.jl pull request #189
Opened 2023-04-28 13:13 UTC by plerouxanyon

Closes #149

2023-04-28 15:21 UTC, fSosaRey requested changes
in getting_started.md, it would be nice to include a Bloch sphere rendering of a Ket.

2023-04-28 17:17 UTC, plerouxanyon commented
> in getting_started.md, it would be nice to include a Bloch sphere rendering of a Ket.

The getting_started.md example is of a Bell state and not representable on a Bloch sphere. Do you have a suggestion on how to incorporate it?

2023-04-28 17:47 UTC, plerouxanyon commented on docs/src/getting_started.md
> +Once `Snowflake.jl` is released, you can install the latest release using the following command:
I've added a warning for the user mentioning that it will pull an much older version.

2023-05-08 21:27 UTC, alireza-najafi approved these changes
For some reason, I've lost my edits. I will approve this merge request and then try to start a new documentation branch.

2023-05-08 21:28 UTC, merged