Fix/tutorials ci
anyonlabs/Snowflake.jl pull request #279
Opened 2023-06-16 18:19 UTC by fSosaRey

Requires #225 for the following tutorials to be successfully run:

tutorials/
tutorials/
tutorials/
tutorials/tutorials/

2023-06-16 18:25 UTC, fSosaRey commented
once #225 is completed, the tutorials folder coulb be added to the coverage targets

2023-06-16 18:31 UTC, plerouxanyon requested changes

2023-06-16 18:31 UTC, plerouxanyon commented on src/core/quantum_circuit.jl
> +function Base.push!(circuit::QuantumCircuit, gates::Vector{<:AbstractGate})
This function should be named `append!` to be consistent with Julia's `Base.*` methods.

2023-06-17 00:37 UTC, plerouxanyon approved these changes

2023-06-17 00:38 UTC, merged