Feat/anti diagonal gates
anyonlabs/Snowflake.jl pull request #88
Opened 2023-03-22 15:57 UTC by fSosaRey

Merge from branch feat/abstract-phase-gate, and implemented changes mentioned in https://github.com/anyonlabs/Snowflake.jl/pull/73#discussion_r1143438226

2023-03-22 16:03 UTC, fSosaRey commented
coverage drops and documentation fails because Circuits cannot handle Gates and AbstractGates at once. will recover once all AbstractGates are implemented

2023-03-22 21:26 UTC, plerouxanyon requested changes

2023-03-22 21:26 UTC, plerouxanyon commented on test/antiDiagonalGate.jl
> +    @test (exp(-im*θ/2*anti_diag_op)).data ≈ [[0.,-im] [-im,0.]]
Inline theta or define the result in terms of theta.

2023-03-22 21:26 UTC, plerouxanyon commented on test/antiDiagonalGate.jl
> +    @test adjoint(y_operator).data==ComplexF64[im,-im]
Can we test this without reaching into the implementation details? (Test using only the public interface)

2023-03-22 21:26 UTC, plerouxanyon commented on test/diagonalGates.jl
> +    @test adjoint(phase_gate_operator).data≈get_operator(Snowflake.phase_shift(target,-ϕ)).data
Again, can we test this without looking at the implementation detail?

2023-03-22 21:26 UTC, plerouxanyon commented on test/diagonalGates.jl
> +    diagonalGate_N_targets(target_list::Vector{<:Integer}) =
Why is this necessary? It looks like we are testing a test.

2023-03-22 21:26 UTC, plerouxanyon commented on test/diagonalOperator.jl
> +    @test (exp(-im*θ/2*diag_op)).data ≈ [-im,-1.]
Again, inline theta or define result in terms of theta

2023-03-22 21:26 UTC, plerouxanyon commented on test/testFunctions.jl
> +    dim::Integer,
This function seems unnecessary. Can we inline this function?

2023-03-22 21:26 UTC, plerouxanyon commented on src/core/qobj.jl
> +1.0 + 0.0im    .
Can we align the printout of DiagonalOperator?

2023-03-22 21:26 UTC, plerouxanyon commented on src/core/qobj.jl
> +commute(A::DiagonalOperator, B::DiagonalOperator)= A*B-B*A
How is this different from the base commute?

2023-03-22 21:26 UTC, plerouxanyon commented on src/core/qobj.jl
> +anticommute(A::DiagonalOperator, B::DiagonalOperator)=A*B+B*A
Again, how is this different from the base anticommute?

2023-03-24 16:04 UTC, plerouxanyon commented on src/core/qobj.jl
> +get_matrix(op::AbstractOperator) =
Could you add a test for this?

2023-03-24 16:04 UTC, plerouxanyon commented on src/core/qobj.jl
> +<<<<<<< HEAD
This looks like a failed merge or rebase.

2023-03-24 18:24 UTC, plerouxanyon commented on src/core/quantum_gate.jl
> +pi_8_diag(T::Type{<:Complex}=ComplexF64) = DiagonalOperator{2,T}(T[1.,exp(im*pi/4.0)])
This operator should be removed.

2023-03-24 18:28 UTC, plerouxanyon commented
The documentation is also failing.

2023-03-24 19:03 UTC, plerouxanyon commented
Just mentioning here for information: The docs and coverage are failing due to the missing tests and failing documentation of the circuit since the circuit cannot use abstract gates yet.

2023-03-24 19:04 UTC, merged